name: Report a bug
description:
    "Please be prepared to see us through understanding and troubleshooting
    steps, providing configurations and verbose log files, and context and
    behavior experienced."
labels: ["bug", "triage"]
body:
    - type: checkboxes
      attributes:
          label:
              Have you checked for any existing open/closed tickets that are the
              same or similar to your issue?
          description:
              Use search to see if an open or closed issue already exists for
              yor bug. if a closed ticket exists, please link to it in your
              ticket.
          options:
              - label: I've searched far and wide!
                required: true
    - type: checkboxes
      attributes:
          label:
              I have gone to the Discord server for support and/or acknowledge
              that this is a bug and not a support issue
          description:
              If this behavior is a result of not being able to properly
              configure something, for example, please visit our Discord
              (https://discord.gg/jpbUFzS5Wb) prior to making any GitHub Issues.
              these issues are strictly for bugs and feature requests.
          options:
              - label: I've tried to solve this already
                required: true
    - type: textarea
      attributes:
          label: What's happening surrounding the bug? (context)
          description:
              Details about your setup, relevant config options, and which
              clients you are using.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Reproducing the bug
          description: How can we reliably get the bug to present itself
          placeholder: |
              1. Deploy to Docker
              2. Set these options in config.js
              3. Trigger a 'search'
      validations:
          required: false
    - type: textarea
      attributes:
          label: What should be happening?
          description: Tell us the behavior you think should be occurring.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Your setup
          description: |
              Examples:
                - Debian 12.5
                - Torznab via Prowlarr 1.17.0.4440
                - Docker | node | yarn
                - more/misc details here
          value: |
              - OS: 
              - Prowlarr/Jackett: 
              - Docker: 
              - Misc:
          render: markdown
      validations:
          required: true
    - type: textarea
      attributes:
          label: config.js (REDACT SENSITIVE INFORMATION)
          description: |
              Please provide us with the config.js you are using when the bug presented itself. 

              **MAKE SURE YOU REDACT ALL SENSITIVE PASSWORDS, PUBLIC IP ADDRESSES, AND API KEYS.**
      validations:
          required: true
    - type: textarea
      attributes:
          label: verbose logs
          description: |
              In order to facilitate fixing your bug, we need the context and logs surrounding the issue
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
              Additionally, any additional info? Screenshots? References? Anything that will give us more context about the issue you are encountering!
      validations:
          required: true
    - type: checkboxes
      attributes:
          label:
              Failure or refusal to provide the information we require to
              address bugs will result in potential closure of the issue.
          description:
              We require verbose logs and your config.js in order to get a full
              picture of the issue. If you are unable to copy paste text and
              describe what is occurring to resolve it, please do not open a
              ticket. If you require help with any of this please visit our
              discord. (https://discord.gg/jpbUFzS5Wb)
          options:
              - label:
                    I acknowledge that i have searched existing issues, read the
                    documentation and faq, read the logs to see if the answer
                    was provided in error messaging, and attempted to get
                    support via the Discord prior to submitting this issue.
                required: true
